name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ca-central-1 | docker login --username AWS --password-stdin <aws_account_id>.dkr.ecr.ca-central-1.amazonaws.com

      - name: Build Docker Image
        run: |
          docker build -t dp012-app .
          docker tag dp012-app:latest <aws_account_id>.dkr.ecr.ca-central-1.amazonaws.com/dp012-app-repo:latest

      - name: Push Docker Image to ECR
        run: |
          docker push <aws_account_id>.dkr.ecr.ca-central-1.amazonaws.com/dp012-app-repo:latest

  update_deployment:
    runs-on: ubuntu-latest
    needs: build_and_push_image

    steps:
      - name: Configure kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Update Kubernetes Deployment
        run: |
          kubectl set image deployment/dp012-app-deployment-dp012 dp012-app=<aws_account_id>.dkr.ecr.ca-central-1.amazonaws.com/dp012-app-repo:latest
